// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainee_Details.Models;

#nullable disable

namespace Trainee_Details.Migrations
{
    [DbContext(typeof(TraineeDbContext))]
    partial class TraineeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trainee_Details.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<DateTime?>("AdmissionDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<decimal>("CourseFee")
                        .HasColumnType("money");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            AdmissionDate = new DateTime(2022, 10, 22, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(140),
                            CourseFee = 10314m,
                            CourseName = "Course1",
                            TraineeId = 1
                        },
                        new
                        {
                            CourseId = 2,
                            AdmissionDate = new DateTime(2022, 9, 14, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(204),
                            CourseFee = 38980m,
                            CourseName = "Course2",
                            TraineeId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            AdmissionDate = new DateTime(2022, 10, 17, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(218),
                            CourseFee = 38154m,
                            CourseName = "Course3",
                            TraineeId = 3
                        },
                        new
                        {
                            CourseId = 4,
                            AdmissionDate = new DateTime(2022, 8, 1, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(232),
                            CourseFee = 69384m,
                            CourseName = "Course4",
                            TraineeId = 4
                        },
                        new
                        {
                            CourseId = 5,
                            AdmissionDate = new DateTime(2022, 10, 10, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(244),
                            CourseFee = 88915m,
                            CourseName = "Course5",
                            TraineeId = 5
                        },
                        new
                        {
                            CourseId = 6,
                            AdmissionDate = new DateTime(2022, 7, 16, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(267),
                            CourseFee = 94716m,
                            CourseName = "Course6",
                            TraineeId = 1
                        },
                        new
                        {
                            CourseId = 7,
                            AdmissionDate = new DateTime(2022, 9, 1, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(281),
                            CourseFee = 123242m,
                            CourseName = "Course7",
                            TraineeId = 2
                        },
                        new
                        {
                            CourseId = 8,
                            AdmissionDate = new DateTime(2022, 9, 22, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(294),
                            CourseFee = 115936m,
                            CourseName = "Course8",
                            TraineeId = 3
                        },
                        new
                        {
                            CourseId = 9,
                            AdmissionDate = new DateTime(2022, 9, 1, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(307),
                            CourseFee = 145422m,
                            CourseName = "Course9",
                            TraineeId = 4
                        },
                        new
                        {
                            CourseId = 10,
                            AdmissionDate = new DateTime(2022, 9, 11, 9, 51, 15, 587, DateTimeKind.Local).AddTicks(336),
                            CourseFee = 174790m,
                            CourseName = "Course10",
                            TraineeId = 5
                        });
                });

            modelBuilder.Entity("Trainee_Details.Models.Trainee", b =>
                {
                    b.Property<int>("TraineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraineeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IsRegular")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TraineeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TraineeId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            TraineeId = 1,
                            Age = 25,
                            Gender = 1,
                            Picture = "1jpg",
                            TraineeName = "Trainee 1"
                        },
                        new
                        {
                            TraineeId = 2,
                            Age = 33,
                            Gender = 1,
                            Picture = "2jpg",
                            TraineeName = "Trainee 2"
                        },
                        new
                        {
                            TraineeId = 3,
                            Age = 31,
                            Gender = 2,
                            Picture = "3jpg",
                            TraineeName = "Trainee 3"
                        },
                        new
                        {
                            TraineeId = 4,
                            Age = 21,
                            Gender = 3,
                            Picture = "4jpg",
                            TraineeName = "Trainee 4"
                        },
                        new
                        {
                            TraineeId = 5,
                            Age = 39,
                            Gender = 3,
                            Picture = "5jpg",
                            TraineeName = "Trainee 5"
                        },
                        new
                        {
                            TraineeId = 6,
                            Age = 21,
                            Gender = 4,
                            Picture = "6jpg",
                            TraineeName = "Trainee 6"
                        });
                });

            modelBuilder.Entity("Trainee_Details.Models.Course", b =>
                {
                    b.HasOne("Trainee_Details.Models.Trainee", "Trainee")
                        .WithMany("Courses")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Trainee_Details.Models.Trainee", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
